import io
from datetime import date
from typing import Dict, Any
from xml.sax.saxutils import escape

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors


class PDFReportGenerator:
    """Generate a workout-focused wellness report."""

    @staticmethod
    def generate_report(user_name: str, report_data: Dict[str, Any]) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle("ReportTitle", parent=styles["Heading1"], fontName="Helvetica-Bold", fontSize=22, leading=26, textColor=colors.HexColor("#0284c7"))
        subtitle_style = ParagraphStyle("ReportSubTitle", parent=styles["Normal"], fontName="Helvetica", fontSize=10, leading=14, textColor=colors.HexColor("#64748b"))
        section_heading = ParagraphStyle("SectionHeading", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=14, leading=18, textColor=colors.HexColor("#0f172a"), spaceBefore=12, spaceAfter=6)
        body_style = ParagraphStyle("ReportBody", parent=styles["BodyText"], fontName="Helvetica", fontSize=10, leading=14, textColor=colors.HexColor("#334155"))
        disclaimer_style = ParagraphStyle("DisclaimerStyle", parent=styles["Normal"], fontName="Helvetica-Oblique", fontSize=8, leading=11, textColor=colors.HexColor("#94a3b8"))

        story = [
            Paragraph("AI Personal Wellness & Lifestyle Report", title_style),
            Paragraph(f"Prepared for: <b>{escape(str(user_name))}</b> | Date: {date.today().strftime('%B %d, %Y')}", subtitle_style),
            Spacer(1, 10),
            HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#e2e8f0"), spaceAfter=15),
        ]

        story.append(Paragraph("1. Executive Summary & AI Observations", section_heading))
        obs = report_data.get("ai_observations", "Keep recording workouts to build a useful personal activity history.")
        story.append(Paragraph(f"<b>AI Observation:</b> {escape(str(obs))}", body_style))
        story.append(Spacer(1, 10))

        story.append(Paragraph("2. Workout & Physical Performance Summary", section_heading))
        workouts_completed = report_data.get("workouts_completed", 0)
        avg_form = report_data.get("avg_form_score", 0)
        story.append(Paragraph(f"• Total Workouts Completed: <b>{workouts_completed}</b>", body_style))
        story.append(Paragraph(f"• Average Form Score: <b>{avg_form}%</b>", body_style))
        story.append(Spacer(1, 10))

        story.append(Paragraph("3. Activity Summary", section_heading))
        table_data = [
            ["Metric", "Current Status", "Target"],
            ["Workout Sessions", str(workouts_completed), "Build consistent activity"],
            ["Average Form", f"{avg_form}%", "Maintain good form"],
        ]
        table = Table(table_data, colWidths=[170, 170, 160])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ]))
        story.append(table)
        story.append(Spacer(1, 20))

        story.append(Paragraph("4. Next Suggested Focus", section_heading))
        focus = report_data.get("next_suggested_focus", "Keep your workout routine consistent.")
        story.append(Paragraph(f"• {escape(str(focus))}", body_style))
        story.append(Spacer(1, 25))

        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cbd5e1"), spaceAfter=10))
        story.append(Paragraph("<b>Medical Disclaimer:</b> This report is generated by an AI Personal Health & Wellness Assistant for lifestyle organization, tracking, and educational purposes. It is not a clinical assessment, medical diagnosis, or prescription.", disclaimer_style))

        doc.build(story)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes
